services:
  - type: web
    name: bafurni-homepage
    runtime: static
    buildCommand: echo static
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /sitemap.xml
        name: Content-Type
        value: application/xml; charset=utf-8
